language: node_js
services:
  - mongodb
node_js:
  - "6.11"
before_script:
  - npm install -g bower
  - bower install --force-latest
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true
